//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTests.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchasePayment
    {
        public int PurchasePaymentID { get; set; }
        public int PurchaseID { get; set; }
        public int PaymentID { get; set; }
    
        public virtual Payment Payment { get; set; }
        public virtual Purchase Purchase { get; set; }
    }
}
