//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTests.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPurchas
    {
        public int UserPurchaseID { get; set; }
        public int PurchaseID { get; set; }
        public int UserID { get; set; }
    
        public virtual Purchase Purchase { get; set; }
        public virtual User User { get; set; }
    }
}
