//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Web.Script.Serialization;
using Newtonsoft.Json;

namespace UnitTests.DB
{
  using System;
  using System.Collections.Generic;

  public partial class UserAccount
  {
    public int UserAccountID { get; set; }
    public int UserID { get; set; }
    public int AccountID { get; set; }

    [JsonIgnore]
    [ScriptIgnore]
    public virtual Account Account { get; set; }

    [JsonIgnore]
    [ScriptIgnore]
    public virtual User User { get; set; }
  }
}
